version: "3.1"
services:
  node0:
    networks:
      - cont
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6700:6700"
      - "63790:63790"
    command:
      - server
      - --node-name=node0
      - --node-port=6700
      - --redis-port=63790
  node1:
    networks:
      - cont
    depends_on:
      - node0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6701:6701"
      - "63791:63791"
    command:
      - server
      - --node-name=node1
      - --node-port=6701
      - --node-peers=node0:6700
      - --redis-port=63791
  node2:
    networks:
      - cont
    depends_on:
      - node0
      - node1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6702:6702"
      - "63792:63792"
    command:
      - server
      - --node-name=node2
      - --node-port=6702
      - --node-peers=node0:6700,node1:6701
      - --redis-port=63792

networks:
  cont:
    driver:  bridge
    enable_ipv6: false